name: Bug Report 🐛
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Bug Report 🐛**

        Please fill out the sections below to help everyone identify and fix the bug.

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: Provide a clear and concise description of what you expected to happen.

  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)

  - type: textarea
    id: contact
    attributes:
      label: How can we contact you (optional)
      placeholder: Leave your slack for clarifications or updates.
    validations:
      required: false

  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
        - "No"

  - type: checkboxes
    id: terms
    attributes:
      label: "By submitting this issue, I have confirmed that:"
      options:
        - label: I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.
          required: true

  - type: markdown
    attributes:
      value: |
        **Thank you for reporting this issue!**

        Your contribution is crucial, and we will investigate the bug as soon as possible. We appreciate your effort in improving the project.
