blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://ccextractor.org/public/general/support/
    about: Join the discussions on the CCExtractor Zulip community.
  - name: GSoC
    url: https://ccextractor.org/docs/ideas_page_for_summer_of_code_2024/
    about: You can find more information about the project on the CCextractor website.
  