// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_all_tasks`, `parse_datetime`

Future<String> getAllTasksJson({required String taskdbDirPath}) =>
    RustLib.instance.api.crateApiGetAllTasksJson(taskdbDirPath: taskdbDirPath);

Future<int> deleteTask(
        {required String uuidSt, required String taskdbDirPath}) =>
    RustLib.instance.api
        .crateApiDeleteTask(uuidSt: uuidSt, taskdbDirPath: taskdbDirPath);

Future<int> updateTask(
        {required String uuidSt,
        required String taskdbDirPath,
        required Map<String, String> map}) =>
    RustLib.instance.api.crateApiUpdateTask(
        uuidSt: uuidSt, taskdbDirPath: taskdbDirPath, map: map);

Future<int> addTask(
        {required String taskdbDirPath, required Map<String, String> map}) =>
    RustLib.instance.api
        .crateApiAddTask(taskdbDirPath: taskdbDirPath, map: map);

Future<int> sync_(
        {required String taskdbDirPath,
        required String url,
        required String clientId,
        required String encryptionSecret}) =>
    RustLib.instance.api.crateApiSync(
        taskdbDirPath: taskdbDirPath,
        url: url,
        clientId: clientId,
        encryptionSecret: encryptionSecret);
